# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.4.2"
gem "sinatra", '~> 1.4.7'
gem 'json'
gem 'travis'

group :development, :test do
  gem 'rake', '~> 11.2.2'
end

group :test do
  gem 'minitest', require: 'minitest/autorun'
  gem 'rack-test', require: 'rack/test'
end
