# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem 'json'
gem 'travis'
gem 'time_difference'

group :development, :test do
  gem 'rake'
end

group :test do
  gem 'minitest',  require: 'minitest/autorun'
  gem 'rack-test', require: 'rack/test'
end
